#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=5

banner "DashScope API Key 获取向导"

# ── Stage 1: 登录阿里云（无账号则注册 + 实名认证） ─────────────────────
stage "登录阿里云（没有就注册 + 实名认证）"
say "先要有阿里云账号并完成实名认证，百炼才能开通、才能建 Key。"
open_url "https://bailian.console.aliyun.com/"
step "没登录就先登录；没有账号就点页面上的「免费注册」注册一个。"
step "如未实名认证，按阿里云要求完成个人实名认证（几分钟）。"
note "国际版用户请用 https://bailian-intl.console.aliyun.com/ ，base_url 也会不同。"
pause "登录（并完成实名）后，按 Enter 继续。"

# ── Stage 2: 开通百炼平台服务 + 大模型服务 ─────────────────────────────
stage "开通百炼平台与大模型服务"
say "不先开通服务，「创建 API Key」按钮是灰的（提示「还未开通模型服务」）。"
open_url "https://bailian.console.aliyun.com/"
step "首次进入百炼会弹出服务协议——阅读后点「同意」，完成平台开通。"
step "如果创建 Key 的按钮是灰的，悬停点「去开通」，勾选协议、点「确认开通」（可领免费额度）。"
pause "确认已开通大模型服务后，按 Enter 继续。"

# ── Stage 3: 创建并复制 API Key ─────────────────────────────────────────
stage "创建并复制 API Key"
say "Key 以 sk- 开头，只在创建弹窗里完整显示一次，务必当场复制。"
open_url "https://bailian.console.aliyun.com/"
step "在控制台右上角找「设置 / 密钥管理 / API-Key」入口（不同版本入口位置略有差异），进入 API-Key 页面。"
step "点「创建 API Key」：归属业务空间选「默认业务空间」；描述可填 AIPodCast；权限选「全部」。点「确定」。"
step "在弹窗里点「复制 API Key」保存到剪贴板。"
warn "关闭弹窗后就看不到完整 Key 了（只剩掩码），丢了只能重置或重建。"
ask_secret DASHSCOPE_API_KEY "粘贴你的 API Key（sk-...）:"
# 防重复粘贴：若前后两半相同（常见于连按两次粘贴），自动取前半
if [[ "${#DASHSCOPE_API_KEY}" -gt 80 ]]; then
  KLEN=${#DASHSCOPE_API_KEY}
  KHALF=$((KLEN / 2))
  if [[ "${DASHSCOPE_API_KEY:0:$KHALF}" == "${DASHSCOPE_API_KEY:$KHALF}" ]]; then
    DASHSCOPE_API_KEY="${DASHSCOPE_API_KEY:0:$KHALF}"
    warn "检测到 key 被粘贴了两次，已自动取前半（${#DASHSCOPE_API_KEY} 字符）。"
  fi
fi

# ── Stage 4: 写入 .env（并确认被 gitignore） ────────────────────────────
stage "把 Key 写进 .env"
say "本地统一用 DASHSCOPE_API_KEY 这个环境变量名（dashscope SDK 默认读取）。"
write_env DASHSCOPE_API_KEY "$DASHSCOPE_API_KEY"
if grep -qE '^\.env' .gitignore 2>/dev/null; then
  note "✓ .env 已在 .gitignore 中，不会误提交。"
else
  warn ".gitignore 未忽略 .env——请手动把 .env 加进 .gitignore。"
fi
pause "按 Enter 继续到最后一步验证。"

# ── Stage 5: 验证 Key 可用 ──────────────────────────────────────────────
stage "验证 Key 可用"
say "用一次模型列表请求验证鉴权（不生成内容、不产生费用）。"
KEY="${DASHSCOPE_API_KEY:-}"
if [[ -z "$KEY" && -f .env ]]; then
  KEY=$(grep -E '^DASHSCOPE_API_KEY=' .env | tail -n1 | cut -d= -f2-)
fi
BASE="${DASHSCOPE_BASE_URL:-}"
if [[ -z "$BASE" && -f .env ]]; then
  BASE=$(grep -E '^DASHSCOPE_BASE_URL=' .env | tail -n1 | cut -d= -f2-)
fi
if [[ -z "$KEY" ]]; then
  warn "没有拿到 Key，跳过验证。请回到第 3 步重建。"
else
  [[ -z "$BASE" ]] && BASE="https://dashscope.aliyuncs.com"
  note "验证端点：$BASE"
  code=$(curl -sS --max-time 15 -o /dev/null -w '%{http_code}' \
    -H "Authorization: Bearer $KEY" "$BASE/compatible-mode/v1/models")
  if [[ "$code" == "200" ]]; then
    note "✓ 鉴权通过（HTTP 200）。Key 已可用。"
  else
    warn "鉴权未通过（HTTP $code）——检查 Key 是否复制完整（sk- 开头）、是否开通服务。若是专属部署，请确认 .env 里 DASHSCOPE_BASE_URL 指向专属端点（llm-...maas.aliyuncs.com）而非标准 dashscope.aliyuncs.com。"
  fi
fi
pause "按 Enter 结束。"

finish
